
module battleSystemApp
{
	module dds
	{
		module idl
		{
		   struct Msg
		   {
		      string unitID;    
		      double lat;
		      double lon;
		      double alt;
		      string message;
		   };
		   #pragma keylist Msg unitID
		};
	};
};